services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      CADDY_INGRESS_NETWORKS: proxy-tier
      ACME_EMAIL: ${ACME_EMAIL}
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_API_SECRET_KEY: ${PORKBUN_API_SECRET_KEY}
    labels:
      caddy: ""
      caddy.email: "{env.ACME_EMAIL}"
      caddy.cert_issuer_0: acme
      caddy.cert_issuer_0.dns: porkbun
      caddy.cert_issuer_0.dns.api_key: "{env.PORKBUN_API_KEY}"
      caddy.cert_issuer_0.dns.api_secret_key: "{env.PORKBUN_API_SECRET_KEY}"
      caddy.cert_issuer_1: internal
    networks:
      - proxy-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy-data:/data
      - caddy-config:/config
    healthcheck:
      test: ["CMD", "/bin/caddy", "validate", "--config", "/config/caddy/autosave.json"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  caddy-data:
  caddy-config:

networks:
  proxy-tier:
    external: true
