services:
  caddy-docker-socket-proxy:
    image: ghcr.io/wollomatic/socket-proxy:1
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    command:
      - -loglevel=info
      - -proxysocketendpoint=/socket/docker.sock
      - -proxysocketendpointfilemode=0660
      - -allowGET=/v[0-9.]+/(version|containers.*|events.*|info|networks.*|services.*|tasks.*)
      - -allowGET=/(_ping|version|containers.*|events.*|info|networks.*|services.*|tasks.*)
      - -allowHEAD=/(_ping|version)
      - -watchdoginterval=3600
      - -stoponwatchdog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy-docker-socket:/socket

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci
    restart: unless-stopped
    depends_on:
      - caddy-docker-socket-proxy
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      CADDY_INGRESS_NETWORKS: proxy-tier
    networks:
      - proxy-tier
    volumes:
      - caddy-docker-socket:/var/run:ro
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-docker-socket:
  caddy-data:
  caddy-config:

networks:
  proxy-tier:
    external: true
