include:
  - path: caddy/docker-compose.yml
  - path: glance/docker-compose.yml
  - path: homepage/docker-compose.yml
  - path: calibre-web-automated/docker-compose.yml
  - path: arcane/docker-compose.yml
  - path: qbittorrent/docker-compose.yml
  - path: qui/docker-compose.yml
  - path: jellyfin/docker-compose.yml
  - path: retroarch/docker-compose.yml
  - path: samba/docker-compose.yml
  - path: withings-sync/docker-compose.yml
