services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
      - ./backups:/backups
      - ./builds:/builds
      - /home/ehtesh/dotfiles/homelab:/home/ehtesh/dotfiles/homelab
    labels:
      caddy: http://arcane.m70q.lan, http://arcane.m.lan
      caddy.reverse_proxy: "{{upstreams 3552}}"

volumes:
  arcane-data:

networks:
  proxy-tier:
    external: true
