services:
  arcane-docker-socket-proxy:
    image: ghcr.io/wollomatic/socket-proxy:1
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    command:
      - -loglevel=info
      - -proxysocketendpoint=/socket/docker.sock
      - -proxysocketendpointfilemode=0660
      - -allowGET=/v[0-9.]+/(version|containers.*|distribution.*|events.*|images.*|info|networks.*|volumes.*)
      - -allowGET=/(_ping|version|containers.*|distribution.*|events.*|images.*|info|networks.*|volumes.*)
      - -allowHEAD=/(_ping|version)
      - -allowPOST=/v[0-9.]+/(containers.*|distribution.*|exec.*|images.*|networks.*|volumes.*)
      - -allowPOST=/(containers.*|distribution.*|exec.*|images.*|networks.*|volumes.*)
      - -allowPUT=/v[0-9.]+/(containers.*|images.*|networks.*|volumes.*)
      - -allowPUT=/(containers.*|images.*|networks.*|volumes.*)
      - -allowDELETE=/v[0-9.]+/(containers.*|images.*|networks.*|volumes.*)
      - -allowDELETE=/(containers.*|images.*|networks.*|volumes.*)
      - -watchdoginterval=3600
      - -stoponwatchdog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - arcane-docker-socket:/socket

  arcane:
    image: ghcr.io/getarcaneapp/manager:latest
    restart: unless-stopped
    depends_on:
      - arcane-docker-socket-proxy
    env_file: .env
    environment:
      APP_URL: http://arcane.${HOSTNAME_BASE:?err}
      PUID: "1000"
      PGID: "1000"
    networks:
      - proxy-tier
    volumes:
      - arcane-docker-socket:/var/run:ro
      - arcane-data:/app/data
      - ./backups:/backups
      - ./builds:/builds
      - ..:/app/data/projects
    labels:
      caddy: http://arcane.${HOSTNAME_BASE:?err}
      caddy.reverse_proxy: "{{upstreams 3552}}"

volumes:
  arcane-docker-socket:
  arcane-data:

networks:
  proxy-tier:
    external: true
