services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:latest
    restart: unless-stopped
    env_file: .env
    environment:
      APP_URL: http://arcane.${HOSTNAME_BASE:?err}
    networks:
      - proxy-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
      - ./backups:/backups
      - ./builds:/builds
      - ..:/app/data/projects
    labels:
      caddy: http://arcane.${HOSTNAME_BASE:?err}
      caddy.reverse_proxy: "{{upstreams 3552}}"

volumes:
  arcane-data:

networks:
  proxy-tier:
    external: true
