#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "pyyaml>=6.0.2",
# ]
# ///
"""Generate docker-compose.override.yml for Arcane.

Inspects homelab/docker-compose.yml and sibling directories to dynamically
generate nested independent project mounts for Arcane, ensuring Arcane's
ephemeral state (.env.global) never pollutes the homelab repository root.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import os
from pathlib import Path
import sys
from typing import Final

import yaml

HEADER_COMMENT: Final[str] = (
    "# Code generated by generate_overrides.py; DO NOT EDIT.\n"
    "# This file maps sibling homelab projects into Arcane's internal workspace\n"
    "# so .env.global remains inside Arcane's volume and never pollutes homelab/.\n"
)


@dataclass(frozen=True, slots=True)
class ProjectMount:
    """Represents a bind-mount from a host project into Arcane."""

    name: str
    host_rel_path: str
    container_path: str

    @classmethod
    def from_name(cls, name: str) -> ProjectMount:
        return cls(
            name=name,
            host_rel_path=f"../{name}",
            container_path=f"/app/data/projects/{name}",
        )

    def to_compose_volume_entry(self) -> str:
        return f"{self.host_rel_path}:{self.container_path}"


def discover_projects(homelab_dir: Path, exclude_name: str = "arcane") -> list[ProjectMount]:
    """Discover all valid Compose projects in homelab/."""
    candidates: set[str] = set()

    # 1. Parse homelab/docker-compose.yml include: directives if present
    root_compose = homelab_dir / "docker-compose.yml"
    if root_compose.is_file():
        try:
            with root_compose.open("r", encoding="utf-8") as f:
                data = yaml.safe_load(f)
            if isinstance(data, dict) and "include" in data:
                for entry in data["include"]:
                    match entry:
                        case {"path": str(p)}:
                            rel_target = Path(p)
                            proj_name = rel_target.parts[0] if rel_target.parts else ""
                            if proj_name and (homelab_dir / proj_name / "docker-compose.yml").is_file():
                                candidates.add(proj_name)
                        case str(p):
                            rel_target = Path(p)
                            proj_name = rel_target.parts[0] if rel_target.parts else ""
                            if proj_name and (homelab_dir / proj_name / "docker-compose.yml").is_file():
                                candidates.add(proj_name)
        except Exception as err:
            print(f"[warning] Failed to parse {root_compose}: {err}", file=sys.stderr)

    # 2. Also scan filesystem for any directory containing docker-compose.yml
    for item in homelab_dir.iterdir():
        if item.is_dir() and item.name != exclude_name and not item.name.startswith((".", "_")):
            if (item / "docker-compose.yml").is_file() or (item / "compose.yaml").is_file():
                candidates.add(item.name)

    candidates.discard(exclude_name)
    return [ProjectMount.from_name(name) for name in sorted(candidates)]


def build_override_content(mounts: list[ProjectMount]) -> str:
    """Build the YAML content for docker-compose.override.yml."""
    doc = {
        "services": {
            "arcane": {
                "volumes": [m.to_compose_volume_entry() for m in mounts],
            }
        }
    }
    dumped = yaml.dump(doc, sort_keys=False, default_flow_style=False)
    return f"{HEADER_COMMENT}\n{dumped}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate docker-compose.override.yml for Arcane project mounts."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether docker-compose.override.yml is up to date without writing.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated configuration to stdout without writing to disk.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    arcane_dir = Path(__file__).resolve().parent
    homelab_dir = arcane_dir.parent
    override_file = arcane_dir / "docker-compose.override.yml"

    mounts = discover_projects(homelab_dir, exclude_name="arcane")
    content = build_override_content(mounts)

    if args.dry_run:
        sys.stdout.write(content)
        return 0

    if args.check:
        if not override_file.is_file():
            print(f"[error] {override_file} does not exist.", file=sys.stderr)
            return 1
        existing = override_file.read_text(encoding="utf-8")
        if existing != content:
            print(f"[error] {override_file} is out of date.", file=sys.stderr)
            return 1
        print(f"[ok] {override_file} is up to date.")
        return 0

    # Atomic write via temporary file
    temp_file = arcane_dir / ".docker-compose.override.yml.tmp"
    temp_file.write_text(content, encoding="utf-8")
    os.replace(temp_file, override_file)

    print(f"Successfully generated {override_file} with {len(mounts)} project mounts:")
    for m in mounts:
        print(f"  + {m.host_rel_path} -> {m.container_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
