services:
  withings-sync:
    image: ghcr.io/jaroslawhartman/withings-sync:latest
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./entrypoint.py:/home/withings-sync/entrypoint.py:ro
    entrypoint: ["/home/withings-sync/entrypoint.py"]
