services:
  withings-sync:
    image: ghcr.io/jaroslawhartman/withings-sync:latest
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./entrypoint.py:/home/withings-sync/entrypoint.py:ro
    entrypoint: ["/home/withings-sync/entrypoint.py"]
    command: ["cron"]
    healthcheck:
      test: ["CMD", "pgrep", "-f", "supercronic"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 20s
