services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.${HOSTNAME_BASE:?err},homepage.${HOSTNAME_ALIAS_BASE:-m.lan}
    networks:
      - proxy-tier
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "-T", "5", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      caddy_0: http://homepage.${HOSTNAME_BASE:?err}, http://homepage.${HOSTNAME_ALIAS_BASE:-m.lan}
      caddy_0.reverse_proxy: "{{upstreams 3000}}"
      caddy_1: https://homepage.${HOSTNAME_BASE:?err}, https://homepage.${HOSTNAME_ALIAS_BASE:-m.lan}
      caddy_1.tls: internal
      caddy_1.reverse_proxy: "{{upstreams 3000}}"

networks:
  proxy-tier:
    external: true
