services:
  rclone-retroarch:
    image: rclone/rclone:latest
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - proxy-tier
    volumes:
      - /srv/retroarch:/data
    command: ["--config", "/dev/null", "serve", "webdav", "/data", "--addr", ":8080", "--timeout", "10m", "--contimeout", "3m", "--log-level", "INFO"]
    labels:
      caddy: http://retroarch.${HOSTNAME_BASE:?err}
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  proxy-tier:
    external: true
